// <auto-generated />
namespace DataMapper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddDataBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDataBase));
        
        string IMigrationMetadata.Id
        {
            get { return "202408281006406_AddDataBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
